namespace: {{ cookiecutter.namespace }}
name: {{ cookiecutter.role_name }}
version: 1.0.0
readme: README.md
authors:
  - {{ cookiecutter.author }}
description: {{ cookiecutter.description }}
license:
  - {{ cookiecutter.license }}
tags: []
dependencies: {}
repository: https://{{ cookiecutter.git_host }}/~{{ cookiecutter.git_user }}/{{ cookiecutter.role_name }}
issues: https://{{ cookiecutter.git_host }}/~{{ cookiecutter.git_user }}/{{ cookiecutter.role_name }}
