---
# - name: Include OS-specific variables
#   ansible.builtin.include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_os_family | lower }}.yml"
#     - "default.yml"
#
# - name: Ensure {{ cookiecutter.role_name }} is configured
#   ansible.builtin.template:
#     src: {{ cookiecutter.role_name }}.conf.j2
#     dest: /etc/{{ cookiecutter.role_name }}.conf
#     owner: root
#     group: root
#     mode: "0644"
#   notify: restart {{ cookiecutter.role_name }}
